language: java

jdk: openjdk8

branches:
  only:
  - new

services:
- mysql

before_install:
- pip install --user codecov
- mysql -u root --password=  < ./init/init.sql

before_script:
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
- mvn clean install -P travis

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - CODECOV_TOKEN=035a54c6-9570-4863-b512-49ed800db266